unit ESTADISTICAS;
{$CODEPAGE UTF8}
interface

uses
  TIPOS_ARCHIVO1,TIPOS_ARCHIVO2,UNIT_ARBOL,VERIFICADORES,UNIT_MANEJO_INTERFACE,SysUtils;
  {○ Distribución (cantidad) de evaluaciones por discapacidad entre dos fechas
    ○ Discapacidades que presentan mayor grado de dificultad entre dos fechas
    ○ CANTIDAD DE AUSENTES Y DE PRESENTES EN EVALUACIONES JENTRE FECHAS}

PROCEDURE LLAMAR_CANT_EVS (VAR ARCHIVO1:T_ARCHIVO1;ARBOL_LEGAJOS:T_PUNT;VAR ARCHIVO2:T_ARCHIVO2;VAR CONTROL:INTEGER;VAR FILA:INTEGER);
PROCEDURE LLAMAR_AUSENCIAS_EVS (VAR ARCHIVO1:T_ARCHIVO1;ARBOL_LEGAJOS:T_PUNT;VAR ARCHIVO2:T_ARCHIVO2;VAR CONTROL:INTEGER;VAR FILA:INTEGER);
PROCEDURE LLAMAR_MAYORDIF_EVS (VAR ARCHIVO1:T_ARCHIVO1;ARBOL_LEGAJOS:T_PUNT;VAR ARCHIVO2:T_ARCHIVO2;VAR CONTROL:INTEGER;VAR FILA:INTEGER);
TYPE
T_VECTOR3 = ARRAY [1..5] OF INTEGER;  //EN CADA POSICION GUARDA NUMEROS, SE USA PARA ALMACENAR 5 CONTADORES

implementation
  PROCEDURE INICIALIZARVECTOR(VAR V:T_VECTOR3);
     VAR
        I:INTEGER;
        BEGIN
            FOR I:=1 TO 5 DO
            V[I]:=0;
        end;

   PROCEDURE MOSTRAR_RESULTADOS(V:T_VECTOR3;FECHADESDE:SHORTSTRING;FECHAHASTA:SHORTSTRING;VAR FILA:INTEGER);
     VAR
        I:INTEGER;
        BEGIN
            FILA:=FILA+3;
            GOTOXYMIO(1,FILA);
            WRITE('Cantidad de evaluaciones por discapacidad entre ',MOSTRAR_FECHA(FECHADESDE),' y ',MOSTRAR_FECHA(FECHAHASTA),' :');
            FOR I:=1 TO 5 DO
            BEGIN
              INC(FILA);
              GOTOXYMIO(1,FILA);
              WRITE('En ',DECIR_NOMBRE_DIF(I),' hay: ',V[I]);
            end;
              FILA:=FILA+2;
             GOTOXYMIO(1,FILA);
             WRITE('OPRIMA CUALQUIER TECLA PARA CONTINUAR');
             READKEY1;
        end;

  PROCEDURE EVALUACIONES_ENTRE_FECHAS(VAR ARCHIVO1:T_ARCHIVO1;ARBOL_LEGAJOS:T_PUNT;VAR ARCHIVO2:T_ARCHIVO2;VAR FECHADESDE:SHORTSTRING;VAR FECHAHASTA:SHORTSTRING;VAR FILA:INTEGER);
   VAR
      POS:CARDINAL;
      X:T_DATO2;
      VECTORCONTADOR:T_VECTOR3;
      I:INTEGER;
     BEGIN
     INICIALIZARVECTOR(VECTORCONTADOR);
     POS:=0;
     IF VERIFICAR_ARCHIVO2(ARCHIVO2)= 1 THEN
     BEGIN
         REPEAT
         SEEK(ARCHIVO2, POS);
         READ(ARCHIVO2,X); //BUSCA EL REGISTRO EN EL ARCHIVO A TRAVÉS DE LA POS Y LO LEE EN X
         IF VERIFICAR_ESTADO(ARCHIVO1,ARBOL_LEGAJOS,X.LEGAJOE)=1 THEN
         BEGIN
         IF ((X.FECHAE)>=FECHADESDE) AND ((X.FECHAE)<= FECHAHASTA) THEN
           BEGIN
           FOR I:=1 TO 5 DO
           BEGIN
             IF X.VALORXDIF[I]>0 THEN     //SI ES MAYOR A CERO ES PORQUE TIENE ASIGNADA UNA NOTA
                 VECTORCONTADOR[I]:= VECTORCONTADOR[I] + 1;
             END;
           END;
         end;
         INC(POS);
         UNTIL(POS>=(FILESIZE(ARCHIVO2))) ;
       CLOSE(ARCHIVO2);
       END;
       MOSTRAR_RESULTADOS(VECTORCONTADOR,FECHADESDE,FECHAHASTA,FILA);
      END;

 PROCEDURE MENU_PEDIR_FECHAS(VAR FECHA_DESDE:SHORTSTRING; VAR FECHA_HASTA: SHORTSTRING; VAR CONTROL:INTEGER;VAR FILA:INTEGER);    //VERIFICAR SI LA FECHA DESDE ES MENOR A LA FECHA HASTA, DAR ERROR

 BEGIN
 FILA:=FILA+2;
 GOTOXYMIO(1,FILA);
 WRITE('Ingrese la fecha incial desde la que quiere buscar: ');
 CARGAR_FECHAS2(FECHA_DESDE,FILA);
 IF FECHA_DESDE <>'ERROR' THEN
   BEGIN
     FILA:=FILA+2;
     GOTOXYMIO(1,FILA);
     WRITE('Fecha Inicial Cargada: ',MOSTRAR_FECHA(FECHA_DESDE));
     FILA:=FILA+3;
     GOTOXYMIO(1,FILA);
     WRITE('Ingrese la fecha límite hasta la que quiere buscar: ');
     CARGAR_FECHAS2(FECHA_HASTA,FILA);
     IF FECHA_HASTA <> 'ERROR' THEN
       BEGIN
       FILA:=FILA+2;
       GOTOXYMIO(1,FILA);
       WRITE('Fecha Límite Cargada: ',MOSTRAR_FECHA(FECHA_HASTA));
        IF FECHA_DESDE <= FECHA_HASTA THEN
          BEGIN
          CONTROL:=1 END ELSE CONTROL:=-6;
       end ELSE
       CONTROL:=-4;
   end ELSE
   CONTROL:=-4;
 END;

  PROCEDURE LLAMAR_CANT_EVS (VAR ARCHIVO1:T_ARCHIVO1;ARBOL_LEGAJOS:T_PUNT;VAR ARCHIVO2:T_ARCHIVO2;VAR CONTROL:INTEGER;VAR FILA:INTEGER);
VAR
   FECHA_DESDE,FECHA_HASTA: SHORTSTRING;
    BEGIN
        CONTROL:=0;
        FECHA_DESDE:='';
        FECHA_HASTA:='';
        FILA:=FILA+2;
        GOTOXYMIO(1,FILA);
        WRITE('***CANTIDAD DE EVALUACIONES POR DIFERENCIA ENTRE DOS FECHAS***');
             MENU_PEDIR_FECHAS(FECHA_DESDE,FECHA_HASTA,CONTROL,FILA);
             IF CONTROL=1 THEN
             EVALUACIONES_ENTRE_FECHAS(ARCHIVO1,ARBOL_LEGAJOS,ARCHIVO2,FECHA_DESDE,FECHA_HASTA,FILA);
    end;


  PROCEDURE MAYORES_DOS_POSICIONES(V:T_VECTOR3; VAR POS1:INTEGER;VAR POS2: INTEGER);  //DEVUELVE LAS DOS MAYORES POSICIONES
VAR
  I, MAX1, MAX2, I1, I2: INTEGER;
BEGIN
  MAX1 := -1000000;
  MAX2 := -1000000;
  I1 := -1;
  I2 := -1;

  FOR I := 1 TO 5 DO
  BEGIN
    IF V[I] > MAX1 THEN
    BEGIN
        MAX2 := MAX1;
        I2 := I1;
        MAX1 := V[I];
        I1 := I;
      END ELSE IF V[I] > MAX2 THEN
        BEGIN
          MAX2 := V[I];
          I2 := I;
        END;
  END;
  POS1 := I1;     //ASIGNA LOS POSICIONES DE LOS 2 MÁXIMOS VALORES DEL VECTOR CONTADOR
  POS2 := I2;
END;


  PROCEDURE COMPARAR_CONTADORES(V:T_VECTOR3;FECHADESDE:SHORTSTRING;FECHAHASTA:SHORTSTRING;VAR FILA:INTEGER);
    VAR
      POS1,POS2,COL:INTEGER;
      SALIDA:STRING;
       BEGIN
         POS1:=0;
         POS2:=0;
         MAYORES_DOS_POSICIONES(V,POS1,POS2);
         FILA:=FILA+3;
         GOTOXYMIO(1,FILA);
         WRITE('RESULTADO: ');
         COL:=LENGTH('RESULTADO: ')+1;
         IF  (V[POS1]=0) AND (V[POS2]=0) THEN
            BEGIN
             SALIDA:=('No hubo desaprobados entre '+MOSTRAR_FECHA(FECHADESDE)+' y '+MOSTRAR_FECHA(FECHAHASTA)) END else
         IF (V[POS1]>0) AND (V[POS2]=0) THEN //si solo en una dificultad hubbo desaprobados
             BEGIN
             SALIDA:=('La discapacidad que representó mayor dificultad entre '+MOSTRAR_FECHA(FECHADESDE)+' y '+MOSTRAR_FECHA(FECHAHASTA)+' fue: '+DECIR_NOMBRE_DIF(POS1)+' con '+IntToStr(V[POS1])+' desaprobados.') END ELSE
             IF (V[POS1]>0) AND (V[POS2]>0) THEN
                BEGIN
                 SALIDA:=('Las dos discapacidades que representaron mayor dificultad entre '+MOSTRAR_FECHA(FECHADESDE)+' y '+MOSTRAR_FECHA(FECHAHASTA)+' fueron: '+DECIR_NOMBRE_DIF(POS1)+' con '+IntToStr(V[POS1])+' desaprobados y '+DECIR_NOMBRE_DIF(POS2)+' con '+IntToStr(V[POS2])+' desaprobados.');
                END;
       RECORTAR(SALIDA,COL,90,FILA,FILA);
       FILA:=FILA+3;
       GOTOXYMIO(1,FILA);
       WRITE('OPRIMA CUALQUIER TECLA PARA CONTINUAR');
       READKEY1;
       end;


    PROCEDURE DIFICULTAD_ENTRE_FECHAS(VAR ARCHIVO1:T_ARCHIVO1;ARBOL_LEGAJOS:T_PUNT;VAR ARCHIVO2:T_ARCHIVO2;VAR FECHADESDE:SHORTSTRING;VAR FECHAHASTA:SHORTSTRING;VAR FILA:INTEGER);
   VAR
      POS:CARDINAL;
      X:T_DATO2;
      VECTORCONTADOR:T_VECTOR3;
      I:INTEGER;
     BEGIN
     INICIALIZARVECTOR(VECTORCONTADOR);
     POS:=0;
     IF VERIFICAR_ARCHIVO2(ARCHIVO2)= 1 THEN
     BEGIN
         REPEAT
         SEEK(ARCHIVO2, POS);
         READ(ARCHIVO2,X); //BUSCA EL REGISTRO EN EL ARCHIVO A TRAVÉS DE LA POS Y LO LEE EN X
         IF VERIFICAR_ESTADO(ARCHIVO1,ARBOL_LEGAJOS,X.LEGAJOE)=1 THEN
         BEGIN
         IF ((X.FECHAE)>=FECHADESDE) AND ((X.FECHAE)<= FECHAHASTA) THEN
           BEGIN
           FOR I:=1 TO 5 DO
           BEGIN
             IF (X.VALORXDIF[I]>1)AND (X.VALORXDIF[I]=2) THEN     //SI TIENE ASIGNADA UNA NOTA Y SI ESTA ES 2(ESTÁ DESAPROBADA)
                 VECTORCONTADOR[I]:= VECTORCONTADOR[I] + 1;
             END;
           END;
         end;
         INC(POS);
         UNTIL(POS>=(FILESIZE(ARCHIVO2))) ;
      CLOSE(ARCHIVO2);
        END;
     COMPARAR_CONTADORES(VECTORCONTADOR,FECHADESDE,FECHAHASTA,FILA);
     end;

PROCEDURE LLAMAR_MAYORDIF_EVS (VAR ARCHIVO1:T_ARCHIVO1;ARBOL_LEGAJOS:T_PUNT;VAR ARCHIVO2:T_ARCHIVO2;VAR CONTROL:INTEGER;VAR FILA:INTEGER);
  VAR FECHA_DESDE,FECHA_HASTA: SHORTSTRING;
    BEGIN
    FILA:=FILA+2;
    GOTOXYMIO(1,FILA);
    WRITE('***DISCAPACIDADES CON MAYOR GRADO DE DIFICULTAD***');
    CONTROL:=0;
        FECHA_DESDE:='';
        FECHA_HASTA:='';
       MENU_PEDIR_FECHAS(FECHA_DESDE,FECHA_HASTA,CONTROL,FILA);
       IF CONTROL=1 THEN
             DIFICULTAD_ENTRE_FECHAS(ARCHIVO1,ARBOL_LEGAJOS,ARCHIVO2,FECHA_DESDE,FECHA_HASTA,FILA);
    end;

PROCEDURE DECIR_CONTADORES(CONT1:INTEGER;CONT2:INTEGER;FECHADESDE:SHORTSTRING;FECHAHASTA:SHORTSTRING;VAR FILA:INTEGER);
VAR
   COL:INTEGER;
 BEGIN
 FILA:=FILA+3;
 GOTOXYMIO(1,FILA);
 WRITE('RESULTADO: ');
 COL:=LENGTH('RESULTADO: ')+1;
 GOTOXYMIO(COL,FILA);
   IF ((CONT1<>1) AND (CONT2<>1)) THEN
   BEGIN
   WRITE('En todas las evaluaciones entre ',MOSTRAR_FECHA(FECHADESDE),' y ',MOSTRAR_FECHA(FECHAHASTA),' hubieron ',CONT1,' PRESENTES y ',CONT2,' AUSENTES.') END ELSE
       IF ((CONT1=1) AND (CONT2<>1)) THEN
       BEGIN
       WRITE('En todas las evaluaciones entre ',MOSTRAR_FECHA(FECHADESDE),' y ',MOSTRAR_FECHA(FECHAHASTA),' hubo un solo PRESENTE y ',CONT2,' AUSENTES.') END ELSE
           IF ((CONT1<>1) AND (CONT2 = 1)) THEN
           BEGIN
           WRITE('En todas las evaluaciones entre ',MOSTRAR_FECHA(FECHADESDE),' y ',MOSTRAR_FECHA(FECHAHASTA),' hubieron ',CONT1,' PRESENTES y un solo AUSENTE.') END;
   FILA:=FILA+3;
   GOTOXYMIO(1,FILA);
   WRITE('OPRIMA CUALQUIER TECLA PARA CONTINUAR');
   READKEY1;
 END;




PROCEDURE AUSENTES_ENTRE_FECHAS(VAR ARCHIVO1:T_ARCHIVO1;ARBOL_LEGAJOS:T_PUNT;VAR ARCHIVO2:T_ARCHIVO2;VAR FECHADESDE:SHORTSTRING;VAR FECHAHASTA:SHORTSTRING; VAR FILA:INTEGER);
   VAR
      POS:CARDINAL;
      X:T_DATO2;
      CONTROL,CONTADOR_AUSENTES,CONTADOR_PRESENTES,I:INTEGER;
     BEGIN
     CONTADOR_PRESENTES:=0;
     CONTADOR_AUSENTES:=0;
     CONTROL:=0;
     POS:=0;
     IF VERIFICAR_ARCHIVO2(ARCHIVO2)=1 THEN
     BEGIN
           REPEAT
             CONTROL:=0;
             SEEK(ARCHIVO2, POS);
             READ(ARCHIVO2,X); //BUSCA EL REGISTRO EN EL ARCHIVO A TRAVÉS DE LA POS Y LO LEE EN X
             IF VERIFICAR_ESTADO(ARCHIVO1,ARBOL_LEGAJOS,X.LEGAJOE)=1 THEN
             BEGIN
               IF ((X.FECHAE)>=FECHADESDE) AND ((X.FECHAE)<= FECHAHASTA) THEN
                 BEGIN
                 FOR I:=1 TO 5 DO
                   BEGIN
                     IF (X.VALORXDIF[I]>0)AND (X.VALORXDIF[I]=1) THEN     //SI TIENE ASIGNADA UNA NOTA Y TIENE AUSENCIAS
                         CONTROL:= -1 ELSE
                           IF (X.VALORXDIF[I]>0)AND (X.VALORXDIF[I]>1) THEN
                             CONTROL:=1;
                   END;
                 END;
              end;
             INC(POS);
             IF CONTROL = -1 THEN
               CONTADOR_AUSENTES:=CONTADOR_AUSENTES + 1 ELSE
                   IF CONTROL= 1 THEN CONTADOR_PRESENTES:= CONTADOR_PRESENTES + 1;
           UNTIL(POS>=(FILESIZE(ARCHIVO2)));
     CLOSE(ARCHIVO2);
     END;
   DECIR_CONTADORES(CONTADOR_PRESENTES,CONTADOR_AUSENTES,FECHADESDE,FECHAHASTA,FILA);
   END;
PROCEDURE LLAMAR_AUSENCIAS_EVS (VAR ARCHIVO1:T_ARCHIVO1;ARBOL_LEGAJOS:T_PUNT;VAR ARCHIVO2:T_ARCHIVO2;VAR CONTROL:INTEGER;VAR FILA:INTEGER);
VAR FECHA_DESDE,FECHA_HASTA: SHORTSTRING;
    BEGIN
      CONTROL:=0;
        FECHA_DESDE:='';
        FECHA_HASTA:='';
        FILA:=FILA+2;
        GOTOXYMIO(1,FILA);
        WRITE('***CANTIDAD DE PRESENTES Y AUSENTES ENTRE DOS FECHAS***');
        MENU_PEDIR_FECHAS(FECHA_DESDE,FECHA_HASTA,CONTROL,FILA);
             IF CONTROL = 1 THEN
             AUSENTES_ENTRE_FECHAS(ARCHIVO1,ARBOL_LEGAJOS,ARCHIVO2,FECHA_DESDE,FECHA_HASTA,FILA);
        end;
end.


