unit LISTADOS;

{$CODEPAGE UTF8}
interface

uses
  sysutils,UNIT_ARBOL, TIPOS_ARCHIVO1,TIPOS_ARCHIVO2,VERIFICADORES, UNIT_MANEJO_INTERFACE, UNIT_PROC_ALUM,UNIT_ARCHIVO_ALUM;

    PROCEDURE LISTADO_APYNOM(ARBOLAPYNOM:T_PUNT;VAR ARCHIVO1:T_ARCHIVO1;VAR FILA:INTEGER);       //SACAR DADOS DE BAJA
    PROCEDURE LISTADO_EVALUACIONES_DE(VAR ARCHIVO2:T_ARCHIVO2; VAR ARCHIVO1:T_ARCHIVO1; ARBOL_LEGAJOS:T_PUNT;LEGAJO:STRING; VAR FILA:INTEGER;VAR VERIFICAR:INTEGER);   //SACAR DADOS DE BAJA
    PROCEDURE LISTADO_ALUM_SEGUN_DIF (VAR ARCHIVO1:T_ARCHIVO1);
    PROCEDURE CONSULTA_EVALUACIONES(VAR ARCHIVO1:T_ARCHIVO1;VAR ARCHIVO2:T_ARCHIVO2;VAR RAIZLEGAJO:T_PUNT; VAR FECHA:SHORTSTRING; VAR CANTIDAD_PRUEBAS:INTEGER;VAR CONTROL:INTEGER; VAR FILA:INTEGER);
implementation
      PROCEDURE DEFINIR_PAGINAS(LIMITE:INTEGER;VAR CANTIDAD_REGISTROS:INTEGER;VAR CANTIDAD_PAGINAS:INTEGER);   //HAY QUE INICIALIZAR CANTIDAD_PAGINAS EN 1
   VAR
    AUX:INTEGER;
    BEGIN
     AUX:=CANTIDAD_REGISTROS;
      IF AUX > LIMITE THEN
           BEGIN
              CANTIDAD_PAGINAS:=CANTIDAD_PAGINAS+1;
              AUX:=AUX-LIMITE;                                 //SI EL LIMITE ES 8 Y LOS REGISTROS SON 24, ENTONCES HARÁ 2 VECES ESTÁ FUNCIÓN, CONTARÁ HASTA 2
              DEFINIR_PAGINAS(LIMITE,AUX,CANTIDAD_PAGINAS);
           end;
    end;



      PROCEDURE MOSTRAR_DATOS_EV2(VAR ARCHIVO1:T_ARCHIVO1; VAR RAIZLEGAJO:T_PUNT; VAR CONTROL:INTEGER; LEGAJO:STRING; X:T_DATO2;VAR FILA:INTEGER);
    VAR
      COL1,COL2,FILAINTERNA,LIMITE:INTEGER;
 BEGIN
  COL1:=40;
  COL2:=10;
  FILAINTERNA:=FILA;
  LIMITE:=COL1-COL2-1;
  GOTOXYMIO(1,FILA);
  WRITELN(LEGAJO);
  GOTOXYMIO(COL2,FILA);
  RECORTAR(X.OBSER,COL2,LIMITE,FILA,FILAINTERNA);
  FILA:=FILA-1;
  MOSTRAR_NOTAS_SEGUN_DIF2(ARCHIVO1,RAIZLEGAJO,CONTROL,LEGAJO,X,FILA,COL1);
  IF FILAINTERNA > FILA THEN
  FILA:=FILAINTERNA;
  INC(FILA);
  GOTOXYMIO(1,FILA);
 WRITE('------------------------------------------------------------------------------------------------------------------------');
 end;



FUNCTION CONTADOR_PRUEBAS(VAR ARCHIVO2:T_ARCHIVO2;VAR ARCHIVO1:T_ARCHIVO1;VAR RAIZLEGAJO:T_PUNT;FECHA:SHORTSTRING):INTEGER;
VAR
 X:T_DATO2;
 POS:CARDINAL;
BEGIN
 POS:=0;
 CONTADOR_PRUEBAS:=0;
IF VERIFICAR_ARCHIVO2(ARCHIVO2)=1 THEN      //YA ABRE EL ARCHIVO SI EXISTE Y TIENE DATOS CARGADOS
      BEGIN
        REPEAT
        SEEK(ARCHIVO2, POS);
        READ(ARCHIVO2,X); //BUSCA EL REGISTRO EN EL ARCHIVO A TRAVÉS DE LA POS Y LO LEE EN X
        IF (X.FECHAE=FECHA)AND (VERIFICAR_ESTADO(ARCHIVO1,RAIZLEGAJO,X.LEGAJOE)=1)THEN    //SI TIENE LA DIF Y SI TIENE EL ESTADO ACTIVO
          BEGIN
           CONTADOR_PRUEBAS:=CONTADOR_PRUEBAS+1;
          END;
        INC(POS);
        UNTIL(POS=(FILESIZE(ARCHIVO2)-1)) ;
      end;
END;


PROCEDURE CONSULTA_EVALUACIONES(VAR ARCHIVO1:T_ARCHIVO1; VAR ARCHIVO2:T_ARCHIVO2;VAR RAIZLEGAJO:T_PUNT; VAR FECHA:SHORTSTRING; VAR CANTIDAD_PRUEBAS:INTEGER;VAR CONTROL:INTEGER; VAR FILA:INTEGER);   //MOSTRAR TODAS LAS EV CORRESPONDIENTE A UNA FECHA
 VAR
    X: T_DATO2;
    POS,CONTADOR_REGISTROS,LIMITE,FILA_INICIAL,PAG,PAG_POSIBLE,EV:INTEGER;
 BEGIN
  CONTADOR_REGISTROS:=0;
  EV:=0;
  PAG_POSIBLE:=1;
  PAG:=1;
  LIMITE:=2;
  CANTIDAD_PRUEBAS:=CONTADOR_PRUEBAS(ARCHIVO2,ARCHIVO1,RAIZLEGAJO,FECHA);
  DEFINIR_PAGINAS(LIMITE,CANTIDAD_PRUEBAS,PAG_POSIBLE);
  FILA:=1;
  GOTOXYMIO(1,FILA);
  IF CANTIDAD_PRUEBAS <> 0 THEN
  BEGIN
    LIMPIAR_PANTALLA;
    WRITE('LISTADO DE EVALUACIONES TOMADAS EL DÍA: ',MOSTRAR_FECHA(FECHA));
    INC(FILA);
    GOTOXYMIO(1,FILA);
    WRITE('------------------------------------------------------------------------------------------------------------------------');
    INC(FILA);
    GOTOXYMIO(1,FILA);
    WRITE('LEGAJOS');
    GOTOXYMIO(10,FILA);
    WRITE('Observaciones');
    GOTOXYMIO(40,FILA);
    WRITE('Notas de la evaluación según diferencias');
    INC(FILA);
    GOTOXYMIO(1,FILA);
    WRITE('------------------------------------------------------------------------------------------------------------------------');
    FILA_INICIAL:=FILA+1;
      POS:=0;
       WHILE NOT EOF(ARCHIVO2) DO //SE HACE UN REPEAT PARA VER SI HAY MAS EVALUACIONES EN ESA FECHA,
       BEGIN
       SEEK(ARCHIVO2, POS);
       READ(ARCHIVO2,X); //BUSCA EL REGISTRO EN EL ARCHIVO A TRAVÉS DE LA POS DE NODO Y LO LEE EN X
       IF (X.FECHAE=FECHA) AND (VERIFICAR_ESTADO(ARCHIVO1,RAIZLEGAJO,X.LEGAJOE)=1) THEN        //SI LA FECHA SON IGUALES ENTONCES MUESTRA EL REGISTRO
         BEGIN
         INC(FILA);
         MOSTRAR_DATOS_EV2(ARCHIVO1,RAIZLEGAJO,CONTROL,X.LEGAJOE,X,FILA);
         CONTADOR_REGISTROS:=CONTADOR_REGISTROS+1;
         EV:=EV+1;
         IF CANTIDAD_PRUEBAS> LIMITE THEN
          BEGIN
            if (CONTADOR_REGISTROS = LIMITE)AND(EV<>CANTIDAD_PRUEBAS) THEN
            BEGIN
            INC(FILA);
            GOTOXYMIO(95,FILA);
            WRITE('PÁGINA ',PAG, ' DE ',PAG_POSIBLE);
            INC(PAG);
            FILA:=FILA+3;
            GOTOXYMIO(1,FILA);
            WRITELN('OPRIMA CUALQUIER TECLA PARA PASAR A LA SUIGUENTE PÁGINA');
            READKEY1;
            LIMPIARHASTA(FILA_INICIAL,FILA);
            FILA:=FILA_INICIAL-1;
            CONTADOR_REGISTROS:=0;
            end;
          end;
         END;
       INC(POS);
       END;      //EL -1 VA PARA QUE NO ESCRIBA DOS VECES EL ÚLTIMO REGISTRO
       INC(FILA);
       GOTOXYMIO(95,FILA);
       WRITE('PÁGINA: ',PAG,' DE: ',PAG_POSIBLE);
       FILA:=FILA+1;
       CLOSE(ARCHIVO2);
     END ELSE FILA:=FILA+6;

  END;





  PROCEDURE MOSTRAR_LISTADO(VAR ARCHIVO1:T_ARCHIVO1; POS:INTEGER;VAR FILA:INTEGER; VAR CONTADOR_ESCRITOS:INTEGER);
     VAR
      X:T_DATO1;
     BEGIN
        X:=LEER_ARCHIVO_EN_POS(ARCHIVO1,POS);
        IF X.ESTADO =1 THEN
        BEGIN
        INC(FILA);
        GOTOXYMIO(1,FILA);
        WRITE(X.APYNOM);
        GOTOXYMIO(42,FILA);
        WRITE(X.LEGAJO);
        MOSTRAR_DIFICULTADES2(X,FILA,60);
        CONTADOR_ESCRITOS:=CONTADOR_ESCRITOS+1;
        INC(FILA);
        GOTOXYMIO(1,FILA);
        WRITE('------------------------------------------------------------------------------------------------------------------------');
        END;
     END;

  PROCEDURE ESCRIBIR_DATOS(VAR FILA:INTEGER);
  BEGIN
      INC(FILA);
      GOTOXYMIO(1,FILA);
      WRITE('------------------------------------------------------------------------------------------------------------------------');
      INC(FILA);
      GOTOXYMIO(1,FILA);
      WRITE('Nombres');
      GOTOXYMIO(42,FILA);
      WRITE('Legajos');
      GOTOXYMIO(60,FILA);
      WRITE('Dificultades del Alumno');
      INC(FILA);
      GOTOXYMIO(1,FILA);
      WRITE('------------------------------------------------------------------------------------------------------------------------');
  END;

   PROCEDURE LISTADO_APYNOM(ARBOLAPYNOM:T_PUNT;VAR ARCHIVO1:T_ARCHIVO1;VAR FILA:INTEGER);
    VAR
     VECTOR:T_VECTOR3;
     I:CARDINAL;
     CANTIDAD,CANTIDAD_EN_ALTA,PAG,PAG_POSIBLE,LIMITE:INTEGER;
     CONTADOR_ESCRITOS:INTEGER;
     BEGIN
     I:=0;
     CONTADOR_ESCRITOS:=0;
     CANTIDAD:=0;
     CANTIDAD_EN_ALTA:=0;
     PAG:=1;
     PAG_POSIBLE:=1;
     LIMITE:=4;//LIMITE DE REGISTROS ESCRITURA
     CANTIDAD_EN_ALTA:=CONTADOR_ALUMNOS_EN_ALTA(ARCHIVO1);
     CANTIDAD:=TAM_ARBOL(ARBOLAPYNOM);  //CANTIDAD DE ALUMNOS EN EL ARBOL
      DEFINIR_PAGINAS(LIMITE,CANTIDAD_EN_ALTA,PAG_POSIBLE);
          LIMPIAR_PANTALLA;
      IF CANTIDAD_EN_ALTA>0 THEN
      BEGIN
      FILA:=0;
      INC(FILA);
      GOTOXYMIO(1,FILA);
      WRITE('LISTADO DE ALUMNOS: ');
      INORDEN2(ARBOLAPYNOM,VECTOR,I);    //APARECEN ALUMNOS YA DADOS DE BAJA PORQUE SE DIERON DE BJA ANTES DE HACER UNA CORRECIÓN
      ESCRIBIR_DATOS(FILA);
      FOR I:= 1 TO CANTIDAD DO
      BEGIN
        MOSTRAR_LISTADO(ARCHIVO1,VECTOR[I],FILA,CONTADOR_ESCRITOS);
        IF CANTIDAD_EN_ALTA> LIMITE THEN
        BEGIN
          if (CONTADOR_ESCRITOS = LIMITE) THEN
          BEGIN
          INC(FILA);
          GOTOXYMIO(95,FILA);
          WRITE('PÁGINA ',PAG, ' DE ',PAG_POSIBLE);
          INC(PAG);
          FILA:=FILA+3;
          GOTOXYMIO(1,FILA);
          WRITELN('OPRIMA CUALQUIER TECLA PARA PASAR A LA SUIGUENTE PÁGINA');
          READKEY1;
          FILA:=0;
          LIMPIAR_PANTALLA;
          ESCRIBIR_DATOS(FILA);
          CONTADOR_ESCRITOS:=0;
          end;
        end;
      end;
      INC(FILA);
      GOTOXYMIO(95,FILA);
      WRITE('PÁGINA ',PAG, ' DE ',PAG_POSIBLE);
      end;
      FILA:=FILA+3;
      GOTOXYMIO(30,FILA);
      WRITE('En total hay ',CANTIDAD_EN_ALTA, ' alumnos en ALTA | OPRIMA CUALQUIER TECLA PARA SALIR ');
      READKEY1;
     END;



   PROCEDURE MOSTRAR_EV(VAR ARCHIVO1:T_ARCHIVO1; VAR ARBOL_LEGAJOS:T_PUNT;VAR VERIFICAR:INTEGER;X:T_DATO2;VAR FILA:INTEGER);
   VAR
    LEGAJO:SHORTSTRING;
    COL1,COL2,LIMITE,FILAINTERNA:INTEGER;
    BEGIN
     LEGAJO:=X.LEGAJOE;
     COL1:=50;
     COL2:=25;
     FILAINTERNA:=FILA;
        LIMITE:=COL1-COL2-1;
        GOTOXYMIO(1,FILA);
        WRITE(MOSTRAR_FECHA(X.FECHAE));
        GOTOXYMIO(25,FILA);
        RECORTAR(X.OBSER,COL2,LIMITE,FILA,FILAINTERNA);
        FILA:=FILA-1;
        MOSTRAR_NOTAS_SEGUN_DIF2(ARCHIVO1,ARBOL_LEGAJOS,VERIFICAR,LEGAJO,X,FILA,COL1);
        IF FILAINTERNA > FILA THEN
        FILA:=FILAINTERNA;
        INC(FILA);
        GOTOXYMIO(1,FILA);
        WRITE('------------------------------------------------------------------------------------------------------------------------');
     END;


      FUNCTION CONTADOR_PRUEBAS(VAR ARCHIVO2:T_ARCHIVO2;LEGAJO:STRING):INTEGER;
   VAR
    X:T_DATO2;
    POS:CARDINAL;
   BEGIN
    POS:=0;
    CONTADOR_PRUEBAS:=0;
    IF VERIFICAR_ARCHIVO2(ARCHIVO2)=1 THEN     //YA ABRE EL ARCHIVO SI EXISTE Y TIENE DATOS CARGADOS
     BEGIN
     REPEAT
     SEEK(ARCHIVO2, POS);
     READ(ARCHIVO2,X); //BUSCA EL REGISTRO EN EL ARCHIVO A TRAVÉS DE LA POS Y LO LEE EN X
     IF (X.LEGAJOE=LEGAJO)THEN    //SI TIENE LA DIF Y SI TIENE EL ESTADO ACTIVO
       BEGIN
        CONTADOR_PRUEBAS:=CONTADOR_PRUEBAS+1;
       END;
     INC(POS);
     UNTIL(POS>=(FILESIZE(ARCHIVO2)));
    end;
   END;


   PROCEDURE LISTADO_EVALUACIONES_DE(VAR ARCHIVO2:T_ARCHIVO2; VAR ARCHIVO1:T_ARCHIVO1; ARBOL_LEGAJOS:T_PUNT;LEGAJO:STRING; VAR FILA:INTEGER;VAR VERIFICAR:INTEGER); //PRIMERO HABRÍA QUE VERIFICAR SI EXISTE ESE LEGAJO BUSCANDO EN EL ARBOL DE LEGAJOS.
     VAR
      POS:CARDINAL;
      X:T_DATO2;
      CONTADOR,FILA_INICIAL,EV:INTEGER;
     BEGIN
     LIMPIAR_PANTALLA;
     POS:=0;
     CONTADOR:=0;
     EV:=0;
     CONTADOR:= CONTADOR_PRUEBAS(ARCHIVO2,LEGAJO);
     FILA:=1;
     GOTOXYMIO(1,FILA);
     WRITELN( '*** DATOS ACTUALES DEL ALUMNO ***');
     MOSTRAR_DATOS(ARCHIVO1,ARBOL_LEGAJOS,LEGAJO,FILA,VERIFICAR);   //VERIFICA SI ESTÁ DADO DE BAJA O NO
     IF (VERIFICAR = 1) and (CONTADOR <>0) THEN
     BEGIN
     FILA:=FILA+2;
     GOTOXYMIO(1,FILA);
     WRITELN('Evaluaciones del alumno con legajo ',LEGAJO,': ');
     FILA:=FILA+2;
     GOTOXYMIO(1,FILA);
     WRITE('Fecha de la Evaluación');
     GOTOXYMIO(25,FILA);
     WRITE('Observación');
     GOTOXYMIO(50,FILA);
     WRITE('Notas de la evaluación según diferencias');
     INC(FILA);
     GOTOXYMIO(1,FILA);
      WRITE('------------------------------------------------------------------------------------------------------------------------');
      FILA_INICIAL:=FILA+1;
         REPEAT
         SEEK(ARCHIVO2, POS);
         READ(ARCHIVO2,X); //BUSCA EL REGISTRO EN EL ARCHIVO A TRAVÉS DE LA POS Y LO LEE EN X
         IF (X.LEGAJOE= LEGAJO)THEN
           BEGIN
           INC(FILA);
           INC(EV);
           GOTOXYMIO(1,FILA);
           MOSTRAR_EV(ARCHIVO1,ARBOL_LEGAJOS,VERIFICAR,X,FILA);
           INC(FILA);
           GOTOXYMIO(1,FILA);
           WRITE('EVALUACIÓN ',EV,' DE ',CONTADOR);   //MUESTRO UNA A LA VEZ PORQUE ES VARIABLE EL NUMERO DE FILAS QUE TIENE POR EL CAMPO OBSERVACIÓN
           IF EV <> CONTADOR THEN
             BEGIN
             INC(FILA);
             GOTOXYMIO(1,FILA);
             WRITE('OPRIMA CUALQUIER TECLA PARA PASAR A LA SIGUIENTE EVALUACIÓN');
             READKEY1;
             LIMPIARHASTA(FILA_INICIAL,FILA);
             FILA:=FILA_INICIAL-1;
             END;
           END;
         INC(POS);
         UNTIL(POS>=(FILESIZE(ARCHIVO2))) ;
        CLOSE(ARCHIVO2);
      END ELSE
            IF (CONTADOR = 0) AND (VERIFICAR = 1) THEN     //ESTÁ DE ALTA PERO NO TIENE EVS CARGADAS
              VERIFICAR:=-3  //NO HAY EVALUACIONES DEL ALUMNO, SI V =0, EL ALUMNO ESTÁ DADO DE BAJA, SI V=-1 EL LEGAJO NO FUE ENCONTRADO
  end;

   PROCEDURE MOSTRAR_ALUMXDIF (X:T_DATO1;VAR FILA:INTEGER);
   BEGIN

     GOTOXYMIO(5,FILA);
     WRITE(X.APYNOM);
     GOTOXYMIO(35,FILA);
     WRITE(X.LEGAJO);
     GOTOXYMIO(55,FILA);
     WRITE(MOSTRAR_FECHA(X.FECHANAC));
     INC(FILA);
     GOTOXYMIO(1,FILA);
     WRITE('----------------------------------------------------------------------------------');
   end;
   FUNCTION CONTADOR_ALUMXDIF(VAR ARCHIVO1:T_ARCHIVO1;NUM:INTEGER):INTEGER;
   VAR
    X:T_DATO1;
    POS:CARDINAL;
   BEGIN
    POS:=0;
    CONTADOR_ALUMXDIF:=0;
     RESET(ARCHIVO1);
     IF ((FILESIZE(ARCHIVO1)=0)) THEN
      CONTADOR_ALUMXDIF:=0 ELSE
     BEGIN
     REPEAT
     SEEK(ARCHIVO1, POS);
     READ(ARCHIVO1,X); //BUSCA EL REGISTRO EN EL ARCHIVO A TRAVÉS DE LA POS Y LO LEE EN X
     IF (X.DIFICULTADES[NUM]=TRUE) AND (X.ESTADO=1) THEN    //SI TIENE LA DIF Y SI TIENE EL ESTADO ACTIVO
       BEGIN
        CONTADOR_ALUMXDIF:=CONTADOR_ALUMXDIF+1;
       END;
     INC(POS);
     UNTIL(POS>=(FILESIZE(ARCHIVO1))) ;
     END;
   END;


   PROCEDURE LISTAR_DIF(VAR ARCHIVO1:T_ARCHIVO1; NUM:INTEGER; VAR FILA:INTEGER; VAR CONTADOR: INTEGER);
      VAR
       POS:CARDINAL;
       X:T_DATO1;
       FILA_INICIAL,CONTADOR_REGISTROS,PAG,LIMITE,CANTIDAD_PAGS:INTEGER;
     BEGIN
     PAG:=1;
     LIMITE:=8;
     CANTIDAD_PAGS:=1;
     CONTADOR_REGISTROS:=0;
     CONTADOR:=CONTADOR_ALUMXDIF(ARCHIVO1,NUM);
     DEFINIR_PAGINAS(LIMITE,CONTADOR,CANTIDAD_PAGS);
     GOTOXYMIO(5,FILA);
     WRITE('Nombre y Apellido');
     GOTOXYMIO(35,FILA);
     WRITE('Legajo');
     GOTOXYMIO(55,FILA);
     WRITE('Fecha de Nacimiento');
     INC(FILA);
     GOTOXYMIO(1,FILA);
     WRITE('----------------------------------------------------------------------------------');
     FILA_INICIAL:=FILA+1;
     IF CONTADOR <>0 THEN
      BEGIN
          POS:=0;
           REPEAT
           SEEK(ARCHIVO1, POS);
           READ(ARCHIVO1,X); //BUSCA EL REGISTRO EN EL ARCHIVO A TRAVÉS DE LA POS Y LO LEE EN X
           IF (X.DIFICULTADES[NUM]=TRUE) AND (X.ESTADO=1) THEN    //SI TIENE LA DIF Y SI TIENE EL ESTADO ACTIVO
             BEGIN
             FILA:=FILA+1;
             MOSTRAR_ALUMXDIF(X,FILA);               //hacer limite de pág de 8 renglones
             CONTADOR_REGISTROS:=CONTADOR_REGISTROS+1;
             END;
           IF CONTADOR > LIMITE THEN
             BEGIN
             IF CONTADOR_REGISTROS = LIMITE THEN     //CADA REGISTRO OCUPA 3 FILAS, 8 x 3 = 24 FILAS QUE LIMPIAR
               BEGIN
                INC(FILA);
                GOTOXYMIO(1,FILA);
                WRITE('PÁGINA: ',PAG,' DE: ',CANTIDAD_PAGS);
                INC(PAG);
                INC(FILA);
                GOTOXYMIO(1,FILA);
                WRITE('OPRIMA CUALQUIER TECLA PARA PASAR A LA SUIGUENTE PÁGINA');
                READKEY1;
                LIMPIARHASTA(FILA_INICIAL,FILA);
                FILA:=FILA_INICIAL-1;
                CONTADOR_REGISTROS:=0;
               end;
             end;
           INC(POS);
           UNTIL(POS>=(FILESIZE(ARCHIVO1))) ;
     END;
     CLOSE(ARCHIVO1);
     INC(FILA);
     GOTOXYMIO(1,FILA);
     WRITE('PÁGINA: ',PAG,' DE: ',CANTIDAD_PAGS);
     end;

     PROCEDURE LISTADO_ALUM_SEGUN_DIF (VAR ARCHIVO1:T_ARCHIVO1);
       VAR
        OP:char;
        FILA,COL,OPCION:INTEGER;
        CONTADOR:INTEGER;
        M,SALIDA:STRING;
       BEGIN
       COL:=1;
       REPEAT
       LIMPIAR_PANTALLA;
       CONTADOR:=0;
       FILA:=1;
      GOTOXYMIO(1,FILA);
      WRITE('Seleccione la dificultad de la quiere una lista de alumnos   :');
      INC(FILA);
      GOTOXYMIO(1,FILA);
      WRITE('1. Problemas del habla y lenguaje:');
      INC(FILA);
      GOTOXYMIO(1,FILA);
      WRITE('2. Dificultad para escribir:');
       INC(FILA);
       GOTOXYMIO(1,FILA);
      WRITE('3. Dificultades de aprendizaje visual:');            //HACER MENU PEDIR BUSCADO
       INC(FILA);
       GOTOXYMIO(1,FILA);
      WRITE('4. Memoria y otras dificultades del pensamiento:');
       INC(FILA);
       GOTOXYMIO(1,FILA);
      WRITE('5. Destrezas sociales inadecuadas:');
       INC(FILA);
       GOTOXYMIO(1,FILA);
      WRITE('0. Salir ');
       (OP):=LEER_OPCION(COL,FILA);
       IF OP IN ['1'..'5'] THEN
         BEGIN
         OPCION:=StrToInt(OP);
         INC(FILA);
         M:='Alumnos con '+ DECIR_NOMBRE_DIF(OPCION)+ ' :';
          GOTOXYMIO(1,FILA);
          WRITE(M);
          FILA:=FILA+2;
         LISTAR_DIF(ARCHIVO1,OPCION,FILA,CONTADOR);
         FILA:=FILA+1;
         if  CONTADOR>1 THEN
         BEGIN
         SALIDA:=('Estos son los ' + IntToStr(CONTADOR) + ' alumnos que tienen ' + DECIR_NOMBRE_DIF(OPCION) +' | PRESIONE CUALQUIER TECLA PARA CONTINUAR');
         END ELSE
             IF CONTADOR = 0 THEN
             BEGIN
             SALIDA:=('No hay alumnos con ' + DECIR_NOMBRE_DIF(OPCION) + ' | PRESIONE CUALQUIER TECLA PARA CONTINUAR');
             END ELSE
                 IF CONTADOR = 1 THEN
                 BEGIN
                 SALIDA:=('Este es el único alumno con ' + DECIR_NOMBRE_DIF(OPCION)+' | PRESIONE CUALQUIER TECLA PARA CONTINUAR');
                 END;
         RECORTAR(SALIDA,COL,80,FILA,FILA);
         READKEY1;
         CONTADOR:=0;
         END ELSE
         BEGIN
          IF OP = '0' THEN
          OP:='0' ELSE
          MAL_INGRESADO(FILA,COL);
         end;
       UNTIL OP='0';
       end;

end.

