unit MENU_PRINCIPAL;
{$CODEPAGE UTF8}
INTERFACE
USES UNIT_ARBOLALUMNO, UNIT_ARBOL,VERIFICADORES,TIPOS_ARCHIVO1,TIPOS_ARCHIVO2, UNIT_MENUS,UNIT_MANEJO_INTERFACE;


PROCEDURE MENU;

IMPLEMENTATION

{LA VENTANA TIENE 120 COL DE ANCHO Y 30 FILAS DE ALTO}
PROCEDURE MENU;
VAR
  ARCHIVO1:T_ARCHIVO1;
  ARCHIVO2:T_ARCHIVO2;
  OPCION:CHAR;
  ARBOL_APYNOM,ARBOL_LEGAJOS:T_PUNT;
  FILA,COL,COL2:INTEGER;
BEGIN
ASSIGN(ARCHIVO1, RUTA1);
ASSIGN(ARCHIVO2,RUTA2);
OPCION:=' ';
COL:=46;
CREARARBOLES_ALUM(ARCHIVO1,ARBOL_APYNOM,ARBOL_LEGAJOS);
REPEAT
    LIMPIAR_PANTALLA;
    //MARCAR_CUADRADO;
     FILA:=5;
     COL2:=50;
     GOTOXYMIO(COL2-7,FILA);
     WRITE('****** MENÚ PRINCIPAL ******');
     fila:=fila+2;
     GOTOXYMIO(COL2,FILA);
     WRITE('1. Alumno');
     INC(FILA);
     GOTOXYMIO(COL2,FILA);
     WRITE('2. Seguimiento');
     INC(FILA);
     GOTOXYMIO(COL2,FILA);
     WRITE('3. Listados');
     INC(FILA);
     GOTOXYMIO(COL2,FILA);
     WRITE('4. Estadísticas');
     INC(FILA);
     GOTOXYMIO(COL2,FILA);
     WRITE('0. Salir');
     FILA:=FILA+2;
     OPCION:=LEER_OPCION(COL,FILA);
    CASE OPCION OF
      '0': OPCION:='0';
      '1': MENU_LEGAJO(ARCHIVO1,ARBOL_LEGAJOS,ARBOL_APYNOM);
      '2': MENU_SEGUIMIENTO(ARCHIVO1,ARCHIVO2,ARBOL_LEGAJOS);
      '3': MENU_LISTADOS(ARCHIVO1,ARCHIVO2,ARBOL_APYNOM,ARBOL_LEGAJOS);
      '4': MENU_ESTADISTICAS(ARCHIVO1,ARBOL_LEGAJOS,ARCHIVO2);
      ELSE BEGIN
             MAL_INGRESADO(FILA,COL);
            end;
    END;
  UNTIL OPCION = '0';
end;
END.
