UNIT TIPOS_ARCHIVO2;
{$CODEPAGE UTF8}

INTERFACE

CONST
RUTA2= 'ruta-Archivo2'; //MODIFICAR PARA SEGÚN SE NECESITE
  N = 200;

TYPE
T_VECTOR2 = ARRAY [1..5] OF 0..5;
T_DATO2 = RECORD          //EVALUACIONES
      LEGAJOE : STRING[10];
      FECHAE: STRING[10];
      VALORXDIF: T_VECTOR2;
      OBSER: STRING[250];
END;

T_ARCHIVO2= FILE OF T_DATO2;     //ARCHIVO EVALUACIONES
IMPLEMENTATION
begin


END.
