UNIT TIPOS_ARCHIVO1;
{$CODEPAGE UTF8}

INTERFACE

CONST
 RUTA1= 'C:\Users\ASUS\Desktop\PROYECTO ALGORITMOS\Archivo1';     //MODIFICAR PARA SEGÚN SE NECESITE
 //RUTA1= 'C:\Users\ASUS\Desktop\Archivo1';
  N = 200;

TYPE
T_VECTOR1 = ARRAY [1..5] OF BOOLEAN;
T_VECTOR3 = ARRAY [1..N] OF CARDINAL;
T_DATO1 = RECORD           //ALUMNO
      APYNOM : STRING[40];
      FECHANAC : STRING[10];
      LEGAJO: STRING[4];  //ES UN NUMERO QUE SE SUMA A MEDIDA QUE SE INGRESAN ESTUDIANTES
      ESTADO: 0..1;
      DIFICULTADES: T_VECTOR1;
END;

T_ARCHIVO1= FILE OF T_DATO1;      //ARCHIVO ALUMNOS
IMPLEMENTATION
begin


END.
