unit UNIT_PROC_EVS;
{$CODEPAGE UTF8}
interface

uses
  UNIT_ARCHIVO_EV,TIPOS_ARCHIVO1,TIPOS_ARCHIVO2, UNIT_ARBOL, VERIFICADORES, UNIT_ARCHIVO_ALUM,UNIT_MANEJO_INTERFACE,SysUtils;

PROCEDURE ALTA_EV(VAR ARCHIVO2:T_ARCHIVO2;VAR ARCHIVO1:T_ARCHIVO1; RAIZLEGAJO:T_PUNT; VAR VERIFICADOR:INTEGER; VAR FILA:INTEGER);
PROCEDURE MODIFICAR_EVALUACION (VAR  ARCHIVO2:T_ARCHIVO2;VAR ARCHIVO1:T_ARCHIVO1; RAIZLEGAJO: T_PUNT; FECHA: SHORTSTRING; LEGAJO:SHORTSTRING; VAR VERIFICADOR:INTEGER; VAR FILA:INTEGER);
PROCEDURE CONSULTAR_EV_PARTICULAR  (VAR ARCHIVO1:T_ARCHIVO1;VAR ARCHIVO2:T_ARCHIVO2;VAR RAIZLEGAJO:T_PUNT;FECHA:SHORTSTRING; LEGAJO:SHORTSTRING; VAR CONTROL:INTEGER;VAR FILA:INTEGER);
implementation


 PROCEDURE INICIALIZAR_VALORACIONESXDIF(VAR X:T_DATO2);
     VAR
   I:INTEGER;
 BEGIN
  FOR I:= 1 TO 5 DO
  BEGIN
   X.VALORXDIF[I]:=0;
  end;
 END;

PROCEDURE INGRESAR_VALORACIONES(VAR X:T_DATO2;VAR ARCHIVO1:T_ARCHIVO1;VAR RAIZALUMNO:T_PUNT; VAR FILA:INTEGER);
        VAR
          NODO1:INTEGER;
          REGALUM:T_DATO1;
          I,FILAINTERNA,COL,NOTA:INTEGER;
          OP:char ;
          RESP:char;
          SALIDA:STRING;
  BEGIN
       NODO1:= PREORDEN(RAIZALUMNO,X.LEGAJOE);
       REGALUM :=LEER_ARCHIVO_EN_POS(ARCHIVO1,NODO1) ;
       INC(FILA);
       GOTOXYMIO(1,FILA);
       WRITE('El alumno:',REGALUM.APYNOM,' con legajo: ',REGALUM.LEGAJO, ' tiene las siguientes difultades: ');
       INC(FILA);
       MOSTRAR_DIFICULTADES2(REGALUM,FILA,5);
       INC(FILA);
       COL:=1;
       NOTA:=5;
       REPEAT
       GOTOXYMIO(1,FILA);
       WRITE('El alumno se presentó? S/N: ');
       READLN(RESP);
       FILAINTERNA:=FILA;
       IF ((RESP = 'n') OR (RESP = 'N')) THEN
        BEGIN
          FOR I:=1 TO 5 DO
          BEGIN
           IF REGALUM.DIFICULTADES[I] = TRUE THEN
            BEGIN
            X.VALORXDIF[I]:=1;  //SE LE ASIGNA AUSENTE EN TODAS LAS DIFICULTADES
            END;
           END;
        END ELSE
            IF ((RESP= 's') OR (RESP= 'S')) THEN
            BEGIN
            LIMPIARLINEA(FILA);
            FOR I:=1 TO 5 DO
              BEGIN
              IF REGALUM.DIFICULTADES[I] = TRUE THEN
               BEGIN
               OP:=('5');
               X.VALORXDIF[I]:=5;
               REPEAT                    //HACER QUE SE ESCRIBA EN EL MISMO LUGAR DONDE SE MOSTRÓ LA PRIMERA VEZ
                  INC(FILAINTERNA);
                  GOTOXYMIO(1,FILAINTERNA);
                  SALIDA:=('Ingrese el valor de la nota en la dificultad: '+DECIR_NOMBRE_DIF(I)+', NOTA ACTUAL: '+DECIR_NOTA_DIF(NOTA));
                  RECORTAR(SALIDA,COL,85,FILAINTERNA,FILAINTERNA);
                  INC(FILAINTERNA);
                  GOTOXYMIO(1,FILAINTERNA);
                  WRITE('Ingrese el 2 si la nota es INSUFICIENTE');
                  INC(FILAINTERNA);
                  GOTOXYMIO(1,FILAINTERNA);
                  WRITE('Ingrese el 3 si la nota es REGULAR');
                  //WRITELN('Ingrese el 4 si la nota es MUY BUENO');
                  INC(FILAINTERNA);
                  GOTOXYMIO(1,FILAINTERNA);
                  WRITE('Ingrese el 4 si la nota es APROBADO');
                  INC(FILAINTERNA);
                  GOTOXYMIO(1,FILAINTERNA);
                  WRITE('Ingrese el 0 si desea pasar a otra Dificultad: ');
                  FILAINTERNA:=FILAINTERNA+1;
                  OP:=LEER_OPCION(COL,FILAINTERNA);
                  IF OP IN ['2'..'4'] THEN
                   BEGIN
                   NOTA:=StrToInt(OP);
                   X.VALORXDIF[I]:=(NOTA);
                   OP:='5';
                   LIMPIARHASTA(FILA,FILAINTERNA);
                   GOTOXYMIO(1,FILA);
                   END ELSE
                           IF OP = '0' THEN
                            BEGIN
                            LIMPIARHASTA(FILA,FILAINTERNA);
                            GOTOXYMIO(1,FILA);
                            NOTA:=5;
                            end ELSE
                            MAL_INGRESADO(FILAINTERNA,COL);
                   FILAINTERNA:=FILA;
                UNTIL OP='0';
               END;
              END;
             FILA:= FILAINTERNA;
     END;
       until ((RESP ='S') OR (RESP='s'))OR ((RESP ='n') OR (RESP='N')) ;
     END;

FUNCTION BUSCAR_EV_PARTICULAR (VAR ARCHIVO2:T_ARCHIVO2; FECHA:STRING; LEGAJO:STRING):INTEGER;   //DEVUELVE LA POS DE LA EV SI EXISTE, SINO DEVUELVE -2
 VAR
X:T_DATO2;
CONTROL,POS:INTEGER;
 BEGIN
  CONTROL:=0;
  POS:=0;
   IF VERIFICAR_ARCHIVO2(ARCHIVO2)=1 THEN
     BEGIN
        WHILE ((NOT EOF(ARCHIVO2)) AND (CONTROL=0))DO
          BEGIN
          SEEK(ARCHIVO2,POS);
          READ(ARCHIVO2,X); //BUSCA EL REGISTRO EN EL ARCHIVO A TRAVÉS DE LA POS DE NODO Y LO LEE EN X
          IF (((X.LEGAJOE = LEGAJO))AND (X.FECHAE = FECHA)) THEN  //si esto se cumple entoces esta evaluación ya existe
            BEGIN
             CONTROL:=1;           //SI CONTROL CAMBIA A 1 ES PORQUE ENCONTRÓ LA EV BUSCADA
            END ELSE
              POS:= POS + 1;       //incrementa la posicion, recorre todo el archivo
          END;
       CLOSE(ARCHIVO2);
       IF CONTROL = 1 THEN
         BUSCAR_EV_PARTICULAR:=POS ELSE   //LE ASIGNA EL VALOR DE LA POSICION A LA FUNCIÓN
           BEGIN
           IF CONTROL = 0 THEN   //NO EXISTE EV CON ESA FECHA Y ESE ELEGAJO
           BUSCAR_EV_PARTICULAR:=-2;
           END;
     end ELSE
     BEGIN
      BUSCAR_EV_PARTICULAR:=-2;
     end;

  END;

FUNCTION INGRESAR_FECHA_EV (VAR ARCHIVO2:T_ARCHIVO2;VAR X:T_DATO2; VAR FILA:INTEGER):INTEGER ;    //MODIFICAR QUE DEVUELA 1,-1 O 0
VAR
AUX:SHORTSTRING;
AUX2:SHORTSTRING;
VERIF:INTEGER;
BEGIN
AUX2:=X.LEGAJOE;
INC(FILA);
GOTOXYMIO(1,FILA);
WRITELN('Ingrese Fecha de la evaluación  (DD/MM/AAAA): ');          //EN EL MENU ANTE EL ERROR PREGUNTAR SI QUIERE VOLVER A INGRESAR DATOS
CARGAR_FECHAS2(AUX,FILA);
IF AUX='ERROR' THEN
 begin
  INGRESAR_FECHA_EV:=-4;
  end ELSE
  BEGIN
  VERIF:=BUSCAR_EV_PARTICULAR(ARCHIVO2,AUX,AUX2);
    IF VERIF <>-2 THEN
     BEGIN
     INGRESAR_FECHA_EV:=-2; //El alumno ya tiene evaluación en esa fecha.
      END ELSE
        IF VERIF = -2 THEN
          BEGIN
            X.FECHAE:= AUX;
            INGRESAR_FECHA_EV:=1;
          END;
   END;
END;

 FUNCTION INGRESAR_LEGAJO_EV (VAR ARCHIVO1:T_ARCHIVO1;RAIZLLEGAJO:T_PUNT;VAR X:T_DATO2; VAR FILA:INTEGER):INTEGER ;
VAR
AUX:SHORTSTRING;
VERIF:INTEGER;
 BEGIN
 INC(FILA);             //EN EL MENU ANTE EL ERROR PREGUNTAR SI QUIERE VOLVER A INGRESAR DATOS
 AUX:=VALIDAR_LEGAJO(FILA,1);
 IF AUX = 'ERROR' THEN
  INGRESAR_LEGAJO_EV:=-7 ELSE
    BEGIN
    VERIF:=VERIFICAR_ESTADO(ARCHIVO1,RAIZLLEGAJO,AUX);
      IF VERIF = -1 THEN
       BEGIN
       INGRESAR_LEGAJO_EV:=-1;//('El legajo del alumno fue mal ingresado o no existe');
       END ELSE
       IF VERIF = 0 THEN
        BEGIN
        INGRESAR_LEGAJO_EV:=0;//('El alumno está dado de baja');
         END ELSE
            IF VERIF = 1 THEN
            BEGIN
              X.LEGAJOE:= AUX;
              INGRESAR_LEGAJO_EV:=1;
            END;
       END;
  END;



PROCEDURE INICIALIZAREV(VAR X:T_DATO2);
BEGIN
  X.FECHAE:='';
  X.LEGAJOE:='';
  INICIALIZAR_VALORACIONESXDIF(X);
  X.OBSER:='';
  END;

FUNCTION INGRESAR_DATOS_EVS (VAR ARCHIVO2:T_ARCHIVO2;VAR ARCHIVO1:T_ARCHIVO1; RAIZLEGAJO:T_PUNT;VAR X:T_DATO2;VAR FILA:INTEGER):INTEGER;
VAR
  CONTROLFECHA,CONTROLLEGAJO:integer;     //PREGUNTAR SI ESTA BIEN USAR UNA VARIABLE QUE SEA PARA CONTROL Y PARA GUARDAR RESULTADOS
BEGIN
  CONTROLLEGAJO:=INGRESAR_LEGAJO_EV(ARCHIVO1,RAIZLEGAJO,X,FILA);  //VERIFICA SI EL ALUMNO EXISTE Y  SI ESTÁ DE ALTA,
  IF CONTROLLEGAJO= 1 THEN                                 //HACER REPEAT O PREGUNTAR SI DESEA VOLVER A INTENTAR SI HAY  ERROR
    BEGIN
      CONTROLFECHA:=INGRESAR_FECHA_EV(ARCHIVO2,X,FILA); //VERIFICA SI EL ALUMNO YA TIENE EV EN ESA FECHA
        IF CONTROLFECHA = 1 THEN
        BEGIN
          INGRESAR_VALORACIONES(X,ARCHIVO1,RAIZLEGAJO,FILA);
          FILA:=FILA+1;  //PORQUE SE ESCRIBE EL CICLO DE OPCIONES DE LAS DIFICULTADES
          GOTOXYMIO(1,FILA);
          WRITE('Ingrese una observación: ');
          READLN(X.OBSER);
           INGRESAR_DATOS_EVS:=1; //SI ES 1 ES POR QUE LOS DATOS FUERON BIEN CARGADOS
         END ELSE
           BEGIN
              IF CONTROLFECHA = -2 THEN
              INGRESAR_DATOS_EVS:=-2;
            END;
     END ELSE
     BEGIN
     CASE CONTROLLEGAJO of
     0:INGRESAR_DATOS_EVS:=0; //EL ALUMNO NO ESTÁ DADO DE BAJA
     -1:INGRESAR_DATOS_EVS:=-1;   //EL ALUMNO NO EXISTE O SU LEGAJO FUE MAL INGRESADO
     END;
     END;
end;


PROCEDURE ALTA_EV(VAR ARCHIVO2:T_ARCHIVO2;VAR ARCHIVO1:T_ARCHIVO1; RAIZLEGAJO:T_PUNT; VAR VERIFICADOR:INTEGER; VAR FILA:INTEGER);
VAR
  X: T_DATO2;
BEGIN
  INICIALIZAREV(X);
  VERIFICADOR:=0;
  VERIFICADOR:= INGRESAR_DATOS_EVS(ARCHIVO2,ARCHIVO1,RAIZLEGAJO,X,FILA);
  IF VERIFICADOR = 1 THEN
    BEGIN
    AGREGAR_EVA_ARCHIVO(ARCHIVO2,X);        //CREA EL REGISTRO DE LA EV
    END;
end;



PROCEDURE MOSTRAR_DATOS_EV(VAR ARCHIVO1:T_ARCHIVO1; VAR RAIZLEGAJO:T_PUNT; VAR CONTROL:INTEGER; LEGAJO:STRING; X:T_DATO2;VAR FILA:INTEGER);
    VAR
      COL,COL_REC,LIMITE_REC:INTEGER;

 BEGIN
  COL:=7;
  FILA:=FILA+2;
  GOTOXYMIO(1,FILA);
  WRITE('EVALUACION:');   //MOSTRAR POR FECHA
  FILA:=FILA+2;
  GOTOXYMIO(1,FILA);
  WRITE('Fecha de de la Evaluación: ', MOSTRAR_FECHA(X.FECHAE));
  FILA:=FILA+2;
  GOTOXYMIO(1,FILA);
  WRITE('Legajo del Alumno: ', X.LEGAJOE);
  FILA:=FILA+2;
  GOTOXYMIO(1,FILA);
  WRITE('Notas: ');
  MOSTRAR_NOTAS_SEGUN_DIF2(ARCHIVO1,RAIZLEGAJO,CONTROL,LEGAJO,X,FILA,COL);
  FILA:=FILA+2;
  GOTOXYMIO(1,FILA);
  WRITE('Observación: ');
  COL_REC:=LENGTH('Observación: ');
  LIMITE_REC:=80;
  RECORTAR(X.OBSER,COL_REC,LIMITE_REC,FILA,FILA);//POR SI ES UNA OBSERVACIÓN MUY LARGA
  CONTROL:=3;
 end;

PROCEDURE CONSULTAR_EV_PARTICULAR  (VAR ARCHIVO1:T_ARCHIVO1;VAR ARCHIVO2:T_ARCHIVO2;VAR RAIZLEGAJO:T_PUNT;FECHA:SHORTSTRING; LEGAJO:SHORTSTRING; VAR CONTROL:INTEGER;VAR FILA:INTEGER);
 VAR
    POS:INTEGER;
    X:T_DATO2;
  BEGIN
   CONTROL:= VERIFICAR_ESTADO(ARCHIVO1,RAIZLEGAJO,LEGAJO);
   IF CONTROL = 1 THEN
   BEGIN
   POS:= BUSCAR_EV_PARTICULAR(ARCHIVO2,FECHA,LEGAJO);
   IF POS = -2 THEN
     CONTROL:=-10 ELSE     //AL ERROR LE ASIGNA QUE NO SE ENCONTRO ESTA BUSQUEDA  PARTICULAR
     BEGIN
       X:=LEER_ARCHIVO_EN_POS_EV(ARCHIVO2,POS);
       MOSTRAR_DATOS_EV(ARCHIVO1,RAIZLEGAJO,CONTROL,LEGAJO,X,FILA);
     END;
   END;
   END;




PROCEDURE OPCIONES_CAMBIO(VAR ARCHIVO2:T_ARCHIVO2;VAR ARCHIVO1:T_ARCHIVO1 ;VAR X: T_DATO2; RAIZLEGAJO:T_PUNT;VAR POSICION:INTEGER;VAR CONTROL:INTEGER;VAR FILA:INTEGER);
 VAR
  OPCION:CHAR;
  COL,COL2:integer;
  BEGIN
    COL:=6;
   COL2:=1;
   REPEAT
     LIMPIAR_PANTALLA;
     CONTROL:=-2;
     FILA:=2;
     GOTOXYMIO(1,FILA);
     WRITE('Fecha de la Evaluación: ', MOSTRAR_FECHA(X.FECHAE), ' (NO SE PUEDE MODIFICAR)');
     FILA:=FILA+1;
     GOTOXYMIO(1,FILA);
     WRITE('Legajo del alumno: ', X.LEGAJOE,  ' (NO SE PUEDE MODIFICAR)');
     FILA:=FILA+2;
     GOTOXYMIO(1,FILA);
     WRITE('SELECCIONE LA OPCIÓN A MODIFICAR: ');
     FILA:=FILA+1;
     GOTOXYMIO(1,FILA);
     WRITE('1. Cambiar alguna Nota: ');
     MOSTRAR_NOTAS_SEGUN_DIF2(ARCHIVO1,RAIZLEGAJO,CONTROL,X.LEGAJOE,X,FILA,COL);
     CONTROL:=2;
     FILA:=FILA+1;
     GOTOXYMIO(1,FILA);
     WRITE('2. Cambiar la Observación: ', X.OBSER);
     FILA:=FILA+1;
     GOTOXYMIO(1,FILA);
     WRITELN('0. Salir');
     FILA:=FILA+1;
     GOTOXYMIO(1,FILA);
     COL2:=1;
     OPCION:=LEER_OPCION(COL2,FILA);
      CASE OPCION OF
        '1':BEGIN
            LIMPIARLINEA(FILA+1);
            FILA:=FILA+2;
            GOTOXYMIO(1,FILA);
            WRITE('CAMBIO DE LAS VALORACIONES DE LA EVALUACIÓN: ');
            INGRESAR_VALORACIONES(X,ARCHIVO1,RAIZLEGAJO,FILA);
            CONTROL:=2;
            END;
        '2':BEGIN
            LIMPIARLINEA(FILA+1);
            FILA:=FILA+3;
            GOTOXYMIO(1,FILA);
            WRITE('CAMBIO DE LA OBSERVACIÓN DE LA EVALUACIÓN: ');
            INC(FILA);
            GOTOXYMIO(1,FILA);
            WRITE('Ingrese una observación: ');
            READ(X.OBSER);    //SI SE MODIFICÓ BIEN SE ASIGNA 2 AL CONTROL
            CONTROL:=2;
            END;
       '0':BEGIN
             OPCION:='0';
           END;
         ELSE  MAL_INGRESADO(FILA,COL);
       END;
      IF (CONTROL=2)AND(OPCION<>'0') THEN
      BEGIN
      SOBREESCRIBIREV(ARCHIVO2,X,POSICION);   // SOBREESCRIBE EL REGISTRO EN LA POS OBTENIDA
      FILA:=FILA+2;
      GOTOXYMIO(1,FILA);
      WRITE('CAMPO MODIFICADO CORRECTAMENTE | PRESIONE CUALQUIER TECLA PARA CONTINUAR');
      READKEY1;
      END;
  UNTIL OPCION = '0';
  end;

PROCEDURE MODIFICAR_EVALUACION (VAR  ARCHIVO2:T_ARCHIVO2;VAR ARCHIVO1:T_ARCHIVO1; RAIZLEGAJO: T_PUNT; FECHA: SHORTSTRING; LEGAJO:SHORTSTRING; VAR VERIFICADOR:INTEGER;VAR FILA:INTEGER);
   VAR
     X: T_DATO2;
     POS:INTEGER;
 BEGIN
  VERIFICADOR :=VERIFICAR_ESTADO(ARCHIVO1,RAIZLEGAJO,LEGAJO);
  IF VERIFICADOR = 1 THEN
  BEGIN
  POS:= BUSCAR_EV_PARTICULAR(ARCHIVO2,FECHA,LEGAJO);
  IF POS = -2 THEN
   BEGIN
     VERIFICADOR:=-10;//SI DEVUELVE -10 ASIGNAR ERROR CORRESPONDIENTE.
     END ELSE
     BEGIN
       X:=LEER_ARCHIVO_EN_POS_EV(ARCHIVO2,POS);
       OPCIONES_CAMBIO(ARCHIVO2,ARCHIVO1,X,RAIZLEGAJO,POS,VERIFICADOR,FILA);
     END;
  end;
 end;

end.
