UNIT UNIT_ARBOLALUMNO;             //PARA GESTIONAR Y ORDERAN REGISTROS DE LOS ARCHIVOS
{$CODEPAGE UTF8}
INTERFACE
USES UNIT_ARBOL,TIPOS_ARCHIVO1;

 PROCEDURE ARCHIVOARBOL_ALUM(VAR ARCHIVO1:T_ARCHIVO1;VAR ARBOLAPYNOM:T_PUNT; VAR ARBOLLEGAJO:T_PUNT);
 PROCEDURE CREARARBOLES_ALUM(VAR ARCHIVO1:T_ARCHIVO1;VAR ARBOLAPYNOM:T_PUNT; VAR ARBOLLEGAJO:T_PUNT);


IMPLEMENTATION
PROCEDURE ARCHIVOARBOL_ALUM(VAR ARCHIVO1:T_ARCHIVO1;VAR ARBOLAPYNOM:T_PUNT; VAR ARBOLLEGAJO:T_PUNT);
VAR
  X:T_DATO1;
  POS:CARDINAL;

BEGIN
  {$I-};
  RESET(ARCHIVO1);
  IF IOResult <> 0 THEN REWRITE(ARCHIVO1);
  WHILE NOT(EOF(ARCHIVO1)) DO
   BEGIN
      READ(ARCHIVO1,X);
      POS:=FILEPOS(ARCHIVO1)-1;
         IF (NOT(ARBOL_LLENO(ARBOLAPYNOM)) AND NOT(ARBOL_LLENO(ARBOLLEGAJO))) THEN
            BEGIN
            AGREGAR_ARBOL(ARBOLLEGAJO,X.LEGAJO,POS);
            AGREGAR_ARBOL(ARBOLAPYNOM,X.APYNOM,POS);
            end;
    END;
     CLOSE(ARCHIVO1);
     {$I+} ;
     END;

PROCEDURE CREARARBOLES_ALUM(VAR ARCHIVO1:T_ARCHIVO1;VAR ARBOLAPYNOM:T_PUNT; VAR ARBOLLEGAJO:T_PUNT);
BEGIN
CREAR_ARBOL(ARBOLAPYNOM);    //inicializa la raíz
CREAR_ARBOL(ARBOLLEGAJO);    //inicializa la raíz
ARCHIVOARBOL_ALUM(ARCHIVO1,ARBOLAPYNOM,ARBOLLEGAJO);
     END;

END.

