UNIT UNIT_MANEJO_INTERFACE;
{$CODEPAGE UTF8}

INTERFACE

USES CRT;

// Procedimiento para interfaz centrada
PROCEDURE CENTRAR_OPCION(FILA: INTEGER; TEXTO: STRING);
PROCEDURE MARCAR_CUADRADO;
PROCEDURE CENTRAR_RESPUESTA_OPCION(FILA: INTEGER; TEXTO: STRING);
PROCEDURE LIMPIARLINEA(FILA: INTEGER);
PROCEDURE LIMPIARLINEACOL(FILA: INTEGER;COL:INTEGER);
PROCEDURE LIMPIARHASTA(FILA1: INTEGER; FILA2: INTEGER);
PROCEDURE PAUSA_MENSAJE(MENSAJE: STRING);
PROCEDURE LIMPIAR_PANTALLA;
PROCEDURE GOTOXYMIO(X:INTEGER; Y: Integer);
PROCEDURE READKEY1;
IMPLEMENTATION


PROCEDURE LIMPIAR_PANTALLA;
BEGIN
CLRSCR;
END;

PROCEDURE MARCAR_CUADRADO;
VAR
  COL,FILA:INTEGER;
BEGIN
  FOR COL:=3 TO 119 DO  //120 CANTIDAD MAXIMA DE COLUMNAS
    BEGIN
      GOTOXY(COL,2);
      WRITE('_');
      GOTOXY(COL,30);
      WRITE('_');
    end;
    FOR FILA:=3 TO 30 DO  //30 CANTIDAD MAXIMA DE FILAS
    BEGIN
      GOTOXY(2,FILA);
      WRITE('|');
      GOTOXY(120,FILA);
      WRITE('|');
    end;
end;

PROCEDURE GOTOXYMIO(X:INTEGER; Y: Integer);
BEGIN
  GOTOXY(X,Y);
END;

PROCEDURE READKEY1;
BEGIN
READKEY;
END;

PROCEDURE CENTRAR_OPCION(FILA: INTEGER; TEXTO: STRING);
BEGIN
GOTOXY((90 - LENGTH(TEXTO)) DIV 2, FILA);
 WRITELN(TEXTO);
END;

PROCEDURE CENTRAR_RESPUESTA_OPCION(FILA: INTEGER; TEXTO: STRING);
BEGIN
  GOTOXY((90 + (LENGTH(TEXTO) DIV 2)) DIV 2, FILA);
END;

PROCEDURE LIMPIARLINEA(FILA: INTEGER);
VAR
  COL: INTEGER;
BEGIN
  COL:=1;        // Mueve el cursor a la columna 1 de la fila indicada
  FOR COL := 1 TO 200 DO      // Recorre todas las columnas (asumiendo pantalla de 80 columnas)
     BEGIN
    GOTOXY(COL,FILA);
    WRITE(' ');              // Sobrescribe con espacios
    END;
  GOTOXY(1, FILA);           // Devuelve el cursor al inicio de esa fila
END;


PROCEDURE LIMPIARLINEACOL(FILA: INTEGER;COL:INTEGER);

BEGIN
  FOR COL := COL TO 200 DO      // Recorre todas las columnas (asumiendo pantalla de 80 columnas)
     BEGIN
    GOTOXY(COL,FILA);
    WRITE(' ');              // Sobrescribe con espacios
    END;
  GOTOXY(COL, FILA);           // Devuelve el cursor al inicio de esa fila
END;

PROCEDURE LIMPIARHASTA(FILA1: INTEGER; FILA2: INTEGER);
VAR
  COL,FILA_AUX: INTEGER;
BEGIN
   IF FILA1= FILA2 THEN
  LIMPIARLINEA(FILA1) ELSE
  BEGIN
  FILA_AUX:=FILA1;
  COL:=1;
  REPEAT
  FOR COL := 1 TO 200 DO
    BEGIN
  GOTOXY(COL, FILA_AUX);
   WRITE(' ');
    end;
  FILA_AUX:=FILA_AUX+1;
  UNTIL FILA_AUX = FILA2;
  end;
END;

PROCEDURE PAUSA_MENSAJE(MENSAJE: STRING);
BEGIN
  CLRSCR;
   WRITELN(STRING(MENSAJE),' | PRESIONE CUALQUIER TECLA PARA CONTINUAR');
  READKEY;
END  ;


END.
