unit UNIT_ARCHIVO_ALUM;

interface

uses
  TIPOS_ARCHIVO1;

 PROCEDURE AGREGAR_ALUM_ARCHIVO(VAR ARCHIVO1:T_ARCHIVO1; X:T_DATO1);
 FUNCTION LEER_ARCHIVO_EN_POS(VAR ARCHIVO1:T_ARCHIVO1; POS:CARDINAL):T_DATO1;
 FUNCTION CONTADOR_ALUMNOS_EN_ALTA(VAR ARCHIVO1:T_ARCHIVO1):INTEGER;
 PROCEDURE SOBREESCRIBIR (VAR ARCHIVO1:T_ARCHIVO1;VAR X:T_DATO1; POSICION:CARDINAL);
 PROCEDURE DAR_DE_BAJA (VAR ARCHIVO1:T_ARCHIVO1; POSICION:INTEGER);
implementation
PROCEDURE AGREGAR_ALUM_ARCHIVO(VAR ARCHIVO1:T_ARCHIVO1;X:T_DATO1);
BEGIN
RESET(ARCHIVO1);
SEEK(ARCHIVO1,FILESIZE(ARCHIVO1));
WRITE(ARCHIVO1,X);
CLOSE(ARCHIVO1);
END;

FUNCTION LEER_ARCHIVO_EN_POS(VAR ARCHIVO1:T_ARCHIVO1; POS:CARDINAL):T_DATO1;
VAR
  X:T_DATO1;
      BEGIN
     RESET(ARCHIVO1);
     SEEK(ARCHIVO1,POS);
     READ(ARCHIVO1, X);
     CLOSE(ARCHIVO1);
     LEER_ARCHIVO_EN_POS:= X;
      END;



FUNCTION CONTADOR_ALUMNOS_EN_ALTA(VAR ARCHIVO1:T_ARCHIVO1):INTEGER;
VAR
  X:T_DATO1;
  POS:CARDINAL;
      BEGIN
     POS:=0;
     CONTADOR_ALUMNOS_EN_ALTA:=0;
     RESET(ARCHIVO1);
     IF FILESIZE(ARCHIVO1)=0 THEN
     CONTADOR_ALUMNOS_EN_ALTA:=0 ELSE
     BEGIN
         WHILE NOT(EOF(ARCHIVO1)) DO
         BEGIN
         SEEK(ARCHIVO1,POS);
         READ(ARCHIVO1, X);
         IF X.ESTADO = 1 THEN
         CONTADOR_ALUMNOS_EN_ALTA:=CONTADOR_ALUMNOS_EN_ALTA+1;
         INC(POS);
         END;
     END;
     CLOSE(ARCHIVO1);
      END;

PROCEDURE SOBREESCRIBIR (VAR ARCHIVO1:T_ARCHIVO1;VAR X:T_DATO1; POSICION:CARDINAL);
 BEGIN
 RESET(ARCHIVO1);
 SEEK(ARCHIVO1,POSICION);
 WRITE(ARCHIVO1,X);
 CLOSE(ARCHIVO1);
 END;


PROCEDURE DAR_DE_BAJA (VAR ARCHIVO1:T_ARCHIVO1; POSICION:INTEGER);
VAR X:T_DATO1;
 BEGIN
 RESET(ARCHIVO1);
 SEEK(ARCHIVO1,POSICION);
 READ(ARCHIVO1,X);
 X.ESTADO:=0;
 SEEK(ARCHIVO1,POSICION);
 WRITE(ARCHIVO1,X);
 CLOSE(ARCHIVO1);
 END;
END.
