unit UNIT_PROC_ALUM;
{$CODEPAGE UTF8}
interface

uses
   UNIT_ARCHIVO_ALUM, UNIT_ARBOLALUMNO, UNIT_ARBOL,TIPOS_ARCHIVO1, VERIFICADORES,UNIT_MANEJO_INTERFACE;

PROCEDURE ALTA_ALUMNO(VAR ARCHIVO1:T_ARCHIVO1; VAR ARBOLAPYNOM:T_PUNT; VAR ARBOLLEGAJO:T_PUNT;LEGAJO:SHORTSTRING;VAR VERIFICAR:INTEGER;VAR FILA:INTEGER);
PROCEDURE MODIFICAR_ALUMNO (VAR  ARCHIVO1:T_ARCHIVO1; VAR ARBOLAPYNOM: T_PUNT; VAR ARBOLLEGAJO:T_PUNT; BUSCADO: SHORTSTRING;VAR VERIFICAR:INTEGER;VAR FILA:INTEGER);
PROCEDURE BAJA_ALUMNO (VAR ARCHIVO1:T_ARCHIVO1;VAR ARBOLLEGAJO:T_PUNT;BUSCADO: SHORTSTRING;VAR VERIFICAR:INTEGER;VAR FILA:INTEGER);
PROCEDURE MOSTRAR_DATOS(VAR ARCHIVO1:T_ARCHIVO1; VAR  RAIZ:T_PUNT; BUSCADO:SHORTSTRING;VAR FILA:INTEGER;VAR VERIFICAR:INTEGER);
implementation



FUNCTION DECIR_VALOR (VAR X: BOOLEAN):STRING;
  BEGIN
     IF X = TRUE THEN
      DECIR_VALOR:='SI' ELSE
      DECIR_VALOR:=('NO');
  end;

  PROCEDURE INGRESAR_DIFICULTADES (VAR X:T_DATO1;VAR FILA:INTEGER);
 VAR
   OPCION:char;
    COL:INTEGER;
   BEGIN
      COL:=1;
      FILA:=FILA+2;
     REPEAT
  GOTOXYMIO(1,FILA);
     WRITELN('Seleccione las Dificultades del Alumno a modificar: ');
     INC(FILA);
  GOTOXYMIO(1,FILA);
     WRITELN('1. Problemas del habla y lenguaje ' + DECIR_VALOR(X.DIFICULTADES[1]));
      INC(FILA);
  GOTOXYMIO(1,FILA);
     WRITELN('2. Dificultad para escribir: ' + DECIR_VALOR(X.DIFICULTADES[2]));
      INC(FILA);
  GOTOXYMIO(1,FILA);
     WRITELN('3. Dificultades de aprendizaje visual: ' + DECIR_VALOR(X.DIFICULTADES[3]));
      INC(FILA);
  GOTOXYMIO(1,FILA);
     WRITELN('4. Memoria y otras dificultades del pensamiento: ' + DECIR_VALOR(X.DIFICULTADES[4]));
      INC(FILA);
  GOTOXYMIO(1,FILA);
     WRITELN('5. Destrezas sociales inadecuadas: ' + DECIR_VALOR(X.DIFICULTADES[5]));
      INC(FILA);
  GOTOXYMIO(1,FILA);
     WRITELN('0. TERMINAR CARGA');
     (OPCION):=LEER_OPCION(COL,FILA);
          CASE OPCION OF
            '1':BEGIN
              IF X.DIFICULTADES[1]=TRUE THEN
              X.DIFICULTADES[1]:=FALSE ELSE
              X.DIFICULTADES[1]:=TRUE;
             end;
            '2': BEGIN
              IF X.DIFICULTADES[2]=TRUE THEN
              X.DIFICULTADES[2]:=FALSE ELSE
              X.DIFICULTADES[2]:=TRUE;
             end;
            '3': BEGIN
              IF X.DIFICULTADES[3]=TRUE THEN
              X.DIFICULTADES[3]:=FALSE ELSE
              X.DIFICULTADES[3]:=TRUE;
             end;
            '4': BEGIN
              IF X.DIFICULTADES[4]=TRUE THEN
              X.DIFICULTADES[4]:=FALSE ELSE
              X.DIFICULTADES[4]:=TRUE;
             end;
            '5': BEGIN
              IF X.DIFICULTADES[5]=TRUE THEN
              X.DIFICULTADES[5]:=FALSE ELSE
              X.DIFICULTADES[5]:=TRUE;
             end;
            '0': begin
              OPCION:='0';
              FILA:=FILA+7;
            end;
            ELSE
              BEGIN
                MAL_INGRESADO(FILA,COL);
              END;
          end;
          LIMPIARLINEA(FILA);
         FILA:=FILA-7;
     UNTIL OPCION='0';
   end;






PROCEDURE INGRESAR_DATOS_ALUM (VAR X:T_DATO1;LEGAJO:SHORTSTRING;VAR CONTROL:INTEGER;VAR FILA:INTEGER);

BEGIN
  INICIALIZAR(X);
  REPEAT
    FILA:=FILA+3;
    GOTOXYMIO(1,FILA);
    WRITE('INGRESO DE DATOS DEL ALUMNO DE LEGAJO: ',LEGAJO);
  FILA:=FILA+2;
  GOTOXYMIO(1,FILA);
  WRITE('Ingrese Apellido y Nombre: ');       //HACER REPEAT O VOLVER A PREGUNTAR EN CASO DE ERRORES DE INGRESO
  READLN(X.APYNOM);
  INC(FILA);
  GOTOXYMIO(1,FILA);
  WRITELN('Ingrese Fecha de Nacimiento (DD/MM/AAAA): ');
  CARGAR_FECHAS2(X.FECHANAC,FILA);
  IF X.FECHANAC = 'ERROR' THEN
  BEGIN
  CONTROL:=-4
  END ELSE
  BEGIN
  X.LEGAJO:=LEGAJO;
  CONTROL:=1;
  INGRESAR_DIFICULTADES(X,FILA);
  IF CONTROL = 1 THEN
      BEGIN
      X.ESTADO:= 1;
      END;
  end;
  until (((CONTROL=1) OR (CONTROL=-4)) OR (CONTROL=-2));
end;

PROCEDURE ALTA_ALUMNO(VAR ARCHIVO1:T_ARCHIVO1; VAR ARBOLAPYNOM:T_PUNT; VAR ARBOLLEGAJO:T_PUNT;LEGAJO:SHORTSTRING;VAR VERIFICAR:INTEGER;VAR FILA:INTEGER);
VAR
  X: T_DATO1;
BEGIN
  VERIFICAR:=-2;
  INGRESAR_DATOS_ALUM(X,LEGAJO,VERIFICAR,FILA);
  IF VERIFICAR = 1 THEN
  BEGIN
  AGREGAR_ALUM_ARCHIVO(ARCHIVO1,X);        //CREA EL REGISTRO DEL ALUMNO
  CREARARBOLES_ALUM(ARCHIVO1,ARBOLAPYNOM,ARBOLLEGAJO);
  END;
end;

PROCEDURE MOSTRAR_DATOS_ALUM(X:T_DATO1;VAR FILA:INTEGER);
 BEGIN

 FILA:=FILA+2;
  GOTOXYMIO(1,FILA);
  WRITELN('Apellido y Nombre: ', X.APYNOM);
  INC(FILA);
  GOTOXYMIO(1,FILA);
  WRITELN('Fecha de Nacimiento: ', MOSTRAR_FECHA(X.FECHANAC));
  INC(FILA);
  GOTOXYMIO(1,FILA);
  WRITELN('Legajo: ', X.LEGAJO);
  INC(FILA);
  GOTOXYMIO(1,FILA);
  WRITE('El alumno:',X.APYNOM,' con legajo: ',X.LEGAJO, ' tiene las siguientes difultades: ');
  INC(FILA);
  MOSTRAR_DIFICULTADES2(X,FILA,5);
 end;


PROCEDURE MOSTRAR_DATOS(VAR ARCHIVO1:T_ARCHIVO1; VAR  RAIZ:T_PUNT; BUSCADO:SHORTSTRING;VAR FILA:INTEGER;VAR VERIFICAR:INTEGER);//PEDIR QUE INGRESE LEGAJO PARA BUSCAR
 VAR
    X: T_DATO1;
    POSICION:INTEGER;
 BEGIN
  VERIFICAR:=VERIFICAR_ESTADO(ARCHIVO1,RAIZ,BUSCADO);
  POSICION:= PREORDEN(RAIZ,BUSCADO);
   IF VERIFICAR = 1 THEN
    BEGIN
    X:=LEER_ARCHIVO_EN_POS(ARCHIVO1,POSICION);
    MOSTRAR_DATOS_ALUM(X,FILA);
    END;
  END;

PROCEDURE CAMBIAR_ESTADO (BUSCADO:STRING;VAR R:STRING;VAR FILA:INTEGER);
VAR
   COL:INTEGER;
  BEGIN
     COL:=1;
     FILA:=FILA+2;
    REPEAT
GOTOXYMIO(1,FILA);
    WRITE('¿Confirma la baja del alumno con legajo: '+ BUSCADO+ '? S/N');
    R:=LEER_OPCION(COL,FILA);
    UNTIL ((LENGTH(R)=1)AND(((R = 's') OR (R = 'S')) OR ((R= 'n') OR (R= 'N'))));
  end;


PROCEDURE BAJA_ALUMNO (VAR ARCHIVO1:T_ARCHIVO1;VAR ARBOLLEGAJO:T_PUNT;BUSCADO: SHORTSTRING;VAR VERIFICAR:INTEGER;VAR FILA:INTEGER); //PEDIR QUE INGRESE LEGAJO PARA MODIFICAR
    VAR
     POSICION:INTEGER;
     RESP:STRING;
   BEGIN
     RESP:='';

  VERIFICAR:=VERIFICAR_ESTADO(ARCHIVO1,ARBOLLEGAJO,BUSCADO);
       IF VERIFICAR = 1 then
       BEGIN
         CAMBIAR_ESTADO(BUSCADO,RESP,FILA);
         IF ((RESP= 'S') OR (RESP= 's')) THEN
         BEGIN
         POSICION:= PREORDEN(ARBOLLEGAJO,BUSCADO);
         DAR_DE_BAJA(ARCHIVO1,POSICION);
         VERIFICAR:=20;    //DADO DE BAJA CORRECTAMENTE
         END;
       END;
     END;



PROCEDURE OPCIONES_CAMBIO(VAR ARCHIVO1:T_ARCHIVO1; VAR ARBOLAPYNOM: T_PUNT; VAR X: T_DATO1;POSICION:INTEGER;VAR CONTROL:INTEGER;VAR FILA:INTEGER);
 VAR
  OPCION:CHAR;
  COL:INTEGER;
  BEGIN
    REPEAT
      LIMPIAR_PANTALLA;
      FILA:=0;
      COL:=1;
      INC(FILA);
      GOTOXYMIO(1,FILA);
      WRITELN('Legajo: ',X.LEGAJO, ' (no se puede modificar)');
      FILA:=FILA+1;
      INC(FILA);
      GOTOXYMIO(1,FILA);
      WRITELN('SELECCIONE LA OPCIÓN A MODIFICAR : ');
      INC(FILA);
      GOTOXYMIO(1,FILA);
      WRITELN('1. Apellido y Nombre: ', X.APYNOM);
      INC(FILA);
      GOTOXYMIO(1,FILA);
       WRITELN('2. Fecha de Nacimiento: ' + MOSTRAR_FECHA(X.FECHANAC));
       INC(FILA);
      GOTOXYMIO(1,FILA);
      WRITE('3. Dificultades: ');
      INC(FILA);
      MOSTRAR_DIFICULTADES2(X,FILA,5);
      INC(FILA);
      GOTOXYMIO(1,FILA);
      WRITELN('0. Salir');
      FILA:=FILA+2;
      OPCION:=LEER_OPCION(COL,FILA);
      CASE OPCION OF
        '1': BEGIN
           ELIMINAR_ARBOL(ARBOLAPYNOM,X.APYNOM);
           INC(FILA);
           GOTOXYMIO(1,FILA);
           WRITE('Ingrese Apellido y Nombre: ');
           READ(X.APYNOM);
           AGREGAR_ARBOL(ARBOLAPYNOM,X.APYNOM,POSICION);    //SOBREESCRIBE EL NUEVO NOMBRRE EN LA POS DEL ARBOL
           CONTROL:=2;
           end;
        '2': BEGIN
          FILA:=FILA+2;
          GOTOXYMIO(1,FILA);
           WRITE('Ingrese Fecha de Nacimiento (DD/MM/AAAA): ');
           CARGAR_FECHAS2(X.FECHANAC,FILA);
            IF X.FECHANAC = 'ERROR' THEN
              BEGIN
                CONTROL:=-4;
                OPCION:='0';
                END ELSE
                CONTROL:=2;
              END;
        '3':BEGIN
            INGRESAR_DIFICULTADES(X,FILA);
            CONTROL:=2;
            end;
        '0':OPCION:='0';
        ELSE
          MAL_INGRESADO(FILA,COL);
      END;
      IF (CONTROL = 2) AND (OPCION <> '0') THEN
      BEGIN
      SOBREESCRIBIR(ARCHIVO1,X,POSICION);  // Sobrescribir el registro en el archivo con los cambios
      FILA:=FILA+2;
      GOTOXYMIO(1,FILA);
      WRITE('CAMPO MODIFICADO CORRECTAMENTE | PRESIONE CUALQUIER TECLA PARA CONTINUAR');
      READKEY1;
      END;
  UNTIL OPCION = '0';  // Salir del menú

  end;


PROCEDURE MODIFICAR_ALUMNO (VAR  ARCHIVO1:T_ARCHIVO1; VAR ARBOLAPYNOM: T_PUNT; VAR ARBOLLEGAJO:T_PUNT; BUSCADO: SHORTSTRING;VAR VERIFICAR:INTEGER;VAR FILA:INTEGER); //PEDIR QUE INGRESE UN NUMERO QUE SEA EL LEGAJO BUSCADO
   VAR
     X: T_DATO1;
     POSICION:INTEGER;
 BEGIN
     POSICION:= PREORDEN(ARBOLLEGAJO,BUSCADO);
     VERIFICAR:=VERIFICAR_ESTADO(ARCHIVO1,ARBOLLEGAJO,BUSCADO);
         IF VERIFICAR=1 THEN
         BEGIN
         X:=LEER_ARCHIVO_EN_POS(ARCHIVO1,POSICION);
         OPCIONES_CAMBIO(ARCHIVO1,ARBOLAPYNOM,X,POSICION,VERIFICAR,FILA);
         END;
    end;
end.

