unit UNIT_ARCHIVO_EV;

interface

uses
  TIPOS_ARCHIVO2;

 PROCEDURE AGREGAR_EVA_ARCHIVO(VAR ARCHIVO2:T_ARCHIVO2; X:T_DATO2);
 FUNCTION LEER_ARCHIVO_EN_POS_EV(VAR ARCHIVO2:T_ARCHIVO2;VAR POS:INTEGER):T_DATO2;
 PROCEDURE SOBREESCRIBIREV (VAR ARCHIVO2:T_ARCHIVO2;VAR X:T_DATO2; POSICION:INTEGER);
implementation
PROCEDURE AGREGAR_EVA_ARCHIVO(VAR ARCHIVO2:T_ARCHIVO2;X:T_DATO2);
VAR
 POS,CONTROL,I:INTEGER;

 AUX:T_DATO2;
BEGIN
POS:=0;
CONTROL:=0;
{$I-};
RESET(ARCHIVO2);
IF IORESULT <> 0 THEN REWRITE(ARCHIVO2);
IF FILESIZE(ARCHIVO2) = 0 THEN
BEGIN
  SEEK(ARCHIVO2,POS);   //  SE ASIGNA LA POSICION OBTENIDA POR EL ACUMULADOR
  WRITE(ARCHIVO2,X);
END ELSE
  BEGIN
  WHILE ((NOT EOF(ARCHIVO2)) AND (CONTROL<>1)) DO
    BEGIN
      SEEK(ARCHIVO2,POS);
      READ(ARCHIVO2,AUX);
      IF X.FECHAE > AUX.FECHAE THEN        //ORDENA DE MENOR A MAYOR, LAS FECHAS MAS RECIENTES SON MENORES
           POS:= POS + 1 ELSE
             CONTROL:=1;               //SI LA FECHA NUEVA ES MENOR O IGUAL SE DETIENE EL CICLO
    END;

  FOR I:= (FILESIZE(ARCHIVO2)-1) DOWNTO POS DO        //MUEVE LOS REGISTROS EN UNA POSICION EXTRA, HASTA EL FINAL DEL ARCHIVO
     BEGIN
        SEEK(ARCHIVO2,I);
        READ(ARCHIVO2,AUX);
        SEEK(ARCHIVO2,I+1);
        WRITE(ARCHIVO2,AUX);
     end;
  SEEK(ARCHIVO2,POS);   //  SE ASIGNA LA POSICION OBTENIDA POR EL ACUMULADOR
  WRITE(ARCHIVO2,X);
  END;
  CLOSE(ARCHIVO2);
  {$I+};
END;


FUNCTION LEER_ARCHIVO_EN_POS_EV(VAR ARCHIVO2:T_ARCHIVO2;VAR POS:INTEGER):T_DATO2;
VAR
   X:T_DATO2;
      BEGIN
      RESET(ARCHIVO2);
     SEEK(ARCHIVO2,POS);
     READ(ARCHIVO2, X);
     LEER_ARCHIVO_EN_POS_EV:=X;
     CLOSE(ARCHIVO2);
      END;


PROCEDURE SOBREESCRIBIREV (VAR ARCHIVO2:T_ARCHIVO2;VAR X:T_DATO2; POSICION:INTEGER);
 BEGIN
 RESET(ARCHIVO2);
 SEEK(ARCHIVO2,POSICION);
 WRITE(ARCHIVO2,X);
 CLOSE(ARCHIVO2);
 END;

end.
